version: "3.5"
networks:
  mynetwork:

services:
  namenode:
    image: concrete13377/namenode:2.0
    deploy:
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 500M
    ports:
      - "1337:1337"
      - "322:322"
    networks:
      - mynetwork


  storage:
    image: concrete13377/storage:2.0
    deploy:
      replicas: 1
#      resources:
#        limits:
#          cpus: "0.3"
#          memory: 500M
    depends_on:
      - "namenode"
    networks:
      - mynetwork


#  client:
#    image: concrete13377/client:2.0
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
#    depends_on:
#      - "namenode"
#    networks:
#      - mynetwork

