version: "3.5"
services:

  namenode:
    image: concrete13377/namenode:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "1337:1337"
      - "322:322"
    networks:
      webnet:
        ipv4_address: 172.28.1.2


  storage:
    image: concrete13377/storage:1.0
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

#    ports:
#      - "1488:1488"
    depends_on:
      - "namenode"
    networks:
      - webnet


#  client:
#    image: concrete13377/client:1.0
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
#    depends_on:
#      - "namenode"
#    networks:
#      webnet:
#        ipv4_address: 172.28.1.4

networks:
  webnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24

#version: '3.5'
  #services:
  #  service1:
  #  image: service1:latest
  #  networks:
  #    service1_net:
  #      ipv4_address: 172.22.0.100
  #networks:
  #  service1_net:
  #    ipam:
  #      driver: default
  #      config:
  #        - subnet: 172.22.0.0/16
