version: "3"
services:
  storage:
    image: concrete13377/storage:1.0
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

    ports:
      - "1488:1488"
    networks:
      - webnet

  namenode:
    image: concrete13377/namenode:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "1337:1337"
      - "322:322"
    networks:
      webnet:
        ipv4_address: 172.28.1.2


  client:
    image: concrete13377/client:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      -webnet


networks:
  webnet:

