version: "3.5"
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  namenode:
    image: concrete13377/namenode:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "1337:1337"
      - "322:322"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.6

  storage:
    image: concrete13377/storage:1.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    depends_on:
      - "namenode"
    networks:
      - mynetwork


#  client:
#    image: concrete13377/client:1.0
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
#    depends_on:
#      - "namenode"
#    networks:
#      -mynetwork

