version: "3.5"
networks:
  mynetwork:

services:
  namenode:
    image: concrete13377/namenode:3.1
    deploy:
      placement:
        constraints:
          - node.role == manager
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 500M
    ports:
      - "1337:1337"
      - "322:322"
    networks:
      - mynetwork


  storage:
    image: concrete13377/storage:3.1
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - replicas-max-per-node 1
#      resources:
#        limits:
#          cpus: "0.3"
#          memory: 500M
    depends_on:
      - "namenode"
    networks:
      - mynetwork

