version: "3.5"
networks:
  mynetwork:

services:
  namenode:
    image: danieldv99/namenode:3.1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 500M
    ports:
      - "1337:1337"
      - "322:322"
    networks:
      - mynetwork


  storage:
    image: danieldv99/storage:3.1
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
#      resources:
#        limits:
#          cpus: "0.3"
#          memory: 500M
    depends_on:
      - "namenode"
    networks:
      - mynetwork

#  client:
#    image: danieldv99/client:3.1
#    deploy:
#      mode: global
#
#    depends_on:
#      - "namenode"
#      - "storage"
