name: Docker Build and Push

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        version: 3.2
        user: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker login --username $user --password $password

        docker build -t=client:$version -f docker/client_dockerfile .
        docker build -t=namenode:$version -f docker/namenode_dockerfile .
        docker build -t=storage:$version -f docker/storage_dockerfile .

        docker tag client:$version $user/client:$version
        docker push $user/client:$version

        docker tag namenode:$version $user/namenode:$version
        docker push $user/namenode:$version

        docker tag storage:$version $user/storage:$version
        docker push $user/storage:$version
        
    - name: Telegram Notify
      env:
#         token: ${{ secrets.TELEGRAM_TOKEN }}
        token: 929739068:AAHsPCZgnB6s_az8tsu4G53ViXktu2Is-0U
#         send_to: ${{ secrets.TELEGRAM_TO }}
        send_to: 127170034
        text: Project is built
        url: https://api.telegram.org/bot$token/sendMessage?chat_id=$send_to&text=$text
      run: |
        echo $token
        echo $send_to
        curl -X POST $url
#       uses: appleboy/telegram-action@0.0.3
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: "Build successful!"
